# Generated by Django 4.2.7 on 2023-11-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingpackage',
            name='link',
        ),
    ]
